### ISSUE TITLE
Hardware PWM?

### ISSUE THREAD

**Issue by schwabix-1311** [cetres/RPi.GPIO#1]
Hi Gustavo, in lack of another way to contact you I'm raising this as an issue.
I understand this repo is a fork from Ben Croston's project on SF. 
However in your latest commit I see a slight hint that you might be working on the addition of hardware PWM. Is this correct?
Any progress?
Do you need support for such?
Markus

**Comment by cetres** [comment]
Hello, Markus
my goal was to make this Ben Croston's library work with my e-ink panel. I made this upgrade to work with Python 3.10 because I am using ArchLinux on Raspberry Pi which require that version of Python. I will not working with PWM support. Nevertheless thank you of your support offer
Gustavo
